- name: setting up env variables
  copy:
    src: bashrc
    dest: /etc/bashrc
    owner: root
    group: root
    mode: '0644'
  shell: source /etc/bashrc


- name: Download Hadoop
  get_url:
    url: https://archive.apache.org/dist/hadoop/core/hadoop-2.7.3/hadoop-2.7.3.tar.gz
    dest: $HOME/
    mode: '0755'

- name: Unarchive Hadoop
  unarchive:
    src: $HOME/hadoop-2.7.3.tar.gz
    dest: $HOME/
    remote_src: yes

- name: Delete the tar.gz file
  shell: rm -rf hadoop-2.7.3.tar.gz

- name: copying slaves and master in to the hadoop conf
  copy:
    src: core-site.xml
    dest: $HOME/hadoop-2.7.3/etc/hadoop/core-site.xml
    
- name: copying slaves and master in to the hadoop conf
  copy:
    src: hdfs-site.xml
    dest: $HOME/hadoop-2.7.3/etc/hadoop/hdfs-site.
    
- name: making directory for name node
  shell: mkdir /root/